Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExamanApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace ExamanApp.Controllers
{
    [Authorize]

    public class ClientsController : Controller
    {
        private readonly Context context;

        public ClientsController(Context context)
        {
            this.context = context;
        }
        // GET: Client
        public ActionResult Index()
        {
            List<Client> Clients = context.Client.ToList();
            foreach (var item in Clients)
            {

                item.Architecte = context.Architecte.Where(e => e.ArchitecteId == item.ArchitecteId).FirstOrDefault();
            }
            return View(Clients);
        }

        // GET: Client/Details/5
        public ActionResult Details(int id)
        {
            var Clients = context.Client.Find(id);
            ViewBag.ListArchitecte = context.Architecte.ToList();

            return View(Clients);
        }

        // GET: Client/Create
        public ActionResult Create()
        {
            ViewBag.ListArchitecte = context.Architecte.ToList();
            return View();
        }

        // POST: Client/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Client client)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    /*if (context.Client.Where(x => x.NomClient == client.NomClient).Count() > 0)
                    {
                        ViewBag.ListArchitecte = context.Client.ToList();
                        ViewBag.error = "Client already exists";
                        return View(client);
                    }*/

                    context.Client.Add(client);
                    context.SaveChanges();
                    return RedirectToAction(nameof(Index));

                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Client/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.ListArchitecte = context.Architecte.ToList();

            Client client = context.Client.Find(id);
            return View(client);
        }

        // POST: Client/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Client client)
        {
            try
            {

                Client existingLivreur = context.Client.Find(id);
                existingLivreur.NomClient = client.NomClient;
                existingLivreur.prenom = client.prenom;
                existingLivreur.addresse = client.addresse;
                existingLivreur.telephone = client.telephone;
                existingLivreur.emailClient = client.emailClient;
                existingLivreur.ArchitecteId = existingLivreur.ArchitecteId;



                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Client/Delete/5
        public ActionResult Delete(int id)
        {
            var client = context.Client.Find(id);
            ViewBag.ListArchitecte = context.Architecte.ToList();

            return View(client);
        }

        // POST: Client/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Client client)
        {
            try
            {
                context.Client.Remove(client);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/FacturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExamanApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace ExamanApp.Controllers
{
    [Authorize]
    public class FacturesController : Controller
    {
        private readonly Context context;

        public FacturesController(Context context)
        {
            this.context = context;
        }

        // GET: Factures
        public ActionResult Index()
        {
            List<Facture> Factures = context.Facture.ToList();
            foreach (var item in Factures)
            {

                item.Projet = context.Projet.Where(e => e.ProjetId == item.ProjetId).FirstOrDefault();
            }
            return View(Factures);
        }
        // GET: Factures/Details/5
        public ActionResult Details(int id)
        {
            var Factures = context.Facture.Find(id);
            ViewBag.ListProjet = context.Projet.ToList();

            return View(Factures);
        }

        // GET: Factures/Create
        public ActionResult Create()
        {
            ViewBag.ListProjet = context.Projet.ToList();
            return View();
        }

        // POST: Factures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Facture facture)
        {
            try
            {
                if (ModelState.IsValid)
                {
                   /* if (context.Facture.Where(x => x.ProjetId  == facture.ProjetId).Count() > 0)
                    {
                        ViewBag.ListProjet = context.Facture.ToList();

                        ViewBag.error = "Facture already exists";
                        return View(facture);
                    }*/
                    context.Facture.Add(facture);
                    context.SaveChanges();
                    return RedirectToAction(nameof(Index));

                }
                return View();
            }
            catch
            {
                return View();
            }
        }


        // GET: Factures/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.ListProjet = context.Projet.ToList();

            Facture facture = context.Facture.Find(id);
            return View(facture);
        }

        // POST: Factures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Facture facture)
        {
            try
            {

                Facture existingLivreur = context.Facture.Find(id);
                existingLivreur.FactureId = facture.FactureId;
                existingLivreur.Montant = facture.Montant;
                existingLivreur.ProjetId = existingLivreur.ProjetId;

                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Factures/Delete/5
        public ActionResult Delete(int id)
        {
            var facture = context.Facture.Find(id);
            ViewBag.ListProjet = context.Projet.ToList();


            return View(facture);
        }

        // POST: Factures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Facture facture)
        {
            try
            {
                context.Facture.Remove(facture);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        
    }
}

Controllers/ProjetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExamanApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Components;

namespace ExamanApp.Controllers
{
    [Authorize]
    public class ProjetsController : Controller
    {
        private readonly Context context;

        public ProjetsController(Context context)
        {
            this.context = context;
        }

        // GET: Projets
        public ActionResult Index()
        {
            List<Projet> Projets = context.Projet.ToList();
            foreach (var item in Projets)
            {

                item.Client = context.Client.Where(e => e.ClientId == item.ClientId).FirstOrDefault();
            }
            return View(Projets);
        }

        // GET: Projets/Details/5
        public ActionResult Details(int id)
        {
            var Projets = context.Projet.Find(id);
            ViewBag.ListClient = context.Client.ToList();
            return View(Projets);
        }

        // GET: Projets/Create
        public ActionResult Create()
        {
            ViewBag.ListClient = context.Client.ToList();
            return View();
        }

        // POST: Projets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Projet projet )
        {
            try
            {
                if (ModelState.IsValid)
                {
                    /*if (context.Projet.Where(x => x.NomProjet == projet.NomProjet).Count() > 0)
                    {
                        ViewBag.ListClient = context.Projet.ToList();

                        ViewBag.error = "Projet already exists";
                        return View(projet);
                    }*/
                   
                    context.Projet.Add(projet);
                    context.SaveChanges();
                    return RedirectToAction(nameof(Index));

                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Projets/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.ListClient = context.Client.ToList();

            Projet projet = context.Projet.Find(id);
            return View(projet);
        }

        // POST: Projets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Projet projet)
        {
            try
            {

                Projet existingLivreur = context.Projet.Find(id);
                existingLivreur.NomProjet = projet.NomProjet;
                existingLivreur.addresseProjet = projet.addresseProjet;
                existingLivreur.Description = projet.Description;
                existingLivreur.StatutProjet = projet.StatutProjet;
                existingLivreur.ClientId = existingLivreur.ClientId;



                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: Projets/Delete/5
        public ActionResult Delete(int id)
        {
            var projet = context.Projet.Find(id);
            ViewBag.ListClient = context.Client.ToList();
            return View(projet);
        }

        // POST: Projets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Projet projet)
        {
            try
            {
                context.Projet.Remove(projet);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Skydash Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/template/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/template/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/template/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/template/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/template/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/template/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/template/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/template/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo mr-5" asp-controller="Home" asp-action="Index"><img src="~/Images/Logo.png" class="mr-2" alt="logo" width="250" /></a>
                <a class="navbar-brand brand-logo-mini" asp-controller="Home" asp-action="Index"><img src="~/Images/Logo.png" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="icon-menu"></span>
                </button>


                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="icon-menu"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_settings-panel.html -->
            <div class="theme-setting-wrapper">
                <div id="settings-trigger"><i class="ti-settings"></i></div>
                <div id="theme-settings" class="settings-panel">
                    <i class="settings-close ti-close"></i>
                    <p class="settings-heading">SIDEBAR SKINS</p>
                    <div class="sidebar-bg-options selected" id="sidebar-light-theme"><div class="img-ss rounded-circle bg-light border mr-3"></div>Light</div>
                    <div class="sidebar-bg-options" id="sidebar-dark-theme"><div class="img-ss rounded-circle bg-dark border mr-3"></div>Dark</div>
                    <p class="settings-heading mt-2">HEADER SKINS</p>
                    <div class="color-tiles mx-0 px-4">
                        <div class="tiles success"></div>
                        <div class="tiles warning"></div>
                        <div class="tiles danger"></div>
                        <div class="tiles info"></div>
                        <div class="tiles dark"></div>
                        <div class="tiles default"></div>
                    </div>
                </div>
            </div>

            <!-- partial -->
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">
                            <i class="icon-grid menu-icon"></i>
                            <span class="menu-title">Home</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a asp-area="" asp-controller="Architectes" asp-action="Index" class="nav-link">
                            <i class="ti-user"></i>&ensp;&ensp;
                            <span class="menu-title"> Architecte</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Clients" asp-action="Index" class="nav-link">
                            <i class="ti-money"></i>&ensp;&ensp;
                            <span class="menu-title">Client</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Projets" asp-action="Index" class="nav-link">
                            <i class="ti-home"></i>&ensp;&ensp;
                            <span class="menu-title">Projet</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Factures" asp-action="Index" class="nav-link">
                            <i class="ti-pencil-alt"></i>&ensp;&ensp;
                            <span class="menu-title">Facture</span>
                        </a>
                    </li>






                </ul>
            </nav>

            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>
            </div>
            <!-- partial -->
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/template/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/template/vendors/chart.js/Chart.min.js"></script>
    <script src="~/template/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/template/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
    <script src="~/template/js/dataTables.select.min.js"></script>

    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/template/js/off-canvas.js"></script>
    <script src="~/template/js/hoverable-collapse.js"></script>
    <script src="~/template/js/template.js"></script>
    <script src="~/template/js/settings.js"></script>
    <script src="~/template/js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/template/js/dashboard.js"></script>
    <script src="~/template/js/Chart.roundedBarCharts.js"></script>
    <!-- End custom js for this page-->
</body>
@await RenderSectionAsync("Scripts", required: false)

</html>